[package]
name = "dinghy-lib"
version = "0.2.16-pre"
authors = ["Mathieu Poumeyrol <mathieu.poumeyrol@snips.ai>"]
license = "MIT/Apache-2.0"
description = "Painless tests on mobile devices"
homepage = "https://medium.com/snips-ai/dinghy-painless-rust-tests-and-benches-on-ios-and-android-c9f94f81d305#.c2sx7two8"
repository = "https://github.com/snipsco/dinghy"
keywords = [
    "tests", "mobile", "ios", "android", "cargo"
]
build="build.rs"
categories = [ "development-tools::cargo-plugins", "development-tools::testing" , "development-tools::profiling" ]

[dependencies]
error-chain = "0.11"
dinghy-helper = { path = "../dinghy-helper" }
log="0.3"
pretty_env_logger="0.1"
clap = "2.26"
cargo = "0.22"
isatty = "0.1"
itertools = "0.7"
plist = "0.2"
regex = "0.2"
json = "0.11"
ignore = "0.2"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
walkdir = "2.0"

[target.'cfg(target_os="macos")'.dependencies]
core-foundation = "0.4"
core-foundation-sys = "0.4"
libc="0.2"
tempdir = "0.3"
