[package]
name = "cargo-dinghy"
version = "0.2.16-pre"
authors = ["Mathieu Poumeyrol <mathieu.poumeyrol@snips.ai>"]
license = "MIT/Apache-2.0"
description = "Painless tests on mobile devices"
homepage = "https://medium.com/snips-ai/dinghy-painless-rust-tests-and-benches-on-ios-and-android-c9f94f81d305#.c2sx7two8"
repository = "https://github.com/snipsco/dinghy"
keywords = [
    "tests", "mobile", "ios", "android", "cargo"
]
categories = [ "development-tools::cargo-plugins", "development-tools::testing" , "development-tools::profiling" ]

[badges]
travis-ci = { repository = "snipsco/dinghy" }

[dependencies]
dinghy-lib = { path="../dinghy-lib" }
error-chain = "0.11"
log = "0.3"
pretty_env_logger = "0.1"
clap = "2.26"
cargo = "0.22"
itertools = "0.7"
